Repository ArmaForces/Boderator, pull requests merged in 2021-08, with the labels that each got.

#53 Upgrade ServerManager package version
  ArmaforcesMissionBot/ArmaforcesMissionBot.csproj
Labels: bugfix

#55 Add aliases for startServer command
  ArmaforcesMissionBot/Modules/Server.cs
Labels: enhancement

#56 Build and push to Docker Hub on commits to master
  .github/workflows/docker.yml
Labels: feature
