Repository ArmaForces/Boderator, pull requests merged in 2021-01, with the labels that each got.

#26 Bot status switching fix
  ArmaforcesMissionBot/Features/RichPresence/GameStatusUpdater.cs
Labels: bugfix

#27 New way of signup owner identification
  ArmaforcesMissionBot/DataClasses/BotConstants.cs
  ArmaforcesMissionBot/Handlers/ArchiveHandler.cs
  ArmaforcesMissionBot/Handlers/LoadupHandler.cs
  ArmaforcesMissionBot/Helpers/SignupHelper.cs
Labels: bugfix, enhancement

#23 Healthcheck
  .gitignore
  ArmaforcesMissionBot/Controllers/HealthController.cs
  ArmaforcesMissionBot/Dockerfile
Labels: enhancement

#28 New command for changing signups name
  ArmaforcesMissionBot/Helpers/SignupHelper.cs
  ArmaforcesMissionBot/Modules/Signups.cs
Labels: enhancement

#30 ArmaServerManager integration
  ArmaforcesMissionBot/ArmaforcesMissionBot.csproj
  ArmaforcesMissionBot/Controllers/ApiController.cs
  ArmaforcesMissionBot/DataClasses/Config.cs
  ArmaforcesMissionBot/DataClasses/MissionsArchiveData.cs
  ArmaforcesMissionBot/DependencyInjection/BoderatorModules.cs
  ArmaforcesMissionBot/Extensions/RestClientExtensions.cs
  ArmaforcesMissionBot/Features/Modsets/Constants/ModsetsApiConstants.cs
  ArmaforcesMissionBot/Features/Modsets/IModsetProvider.cs
  ArmaforcesMissionBot/Features/Modsets/IModsetsApiClient.cs
  ArmaforcesMissionBot/Features/Modsets/Legacy/LegacyModsetProvider.cs
  ArmaforcesMissionBot/Features/Modsets/ModsetProvider.cs
  ArmaforcesMissionBot/Features/Modsets/ModsetsApiClient.cs
  ArmaforcesMissionBot/Features/Modsets/WebModset.cs
  ArmaforcesMissionBot/Features/ServerManager/ServerManagerConfiguration.cs
  ArmaforcesMissionBot/Handlers/CommandHandler.cs
  ArmaforcesMissionBot/Handlers/LoadupHandler.cs
  ArmaforcesMissionBot/Modules/Signups.cs
  ArmaforcesMissionBotSharedClasses/ArmaforcesMissionBotSharedClasses.csproj
  ArmaforcesMissionBotSharedClasses/Mission.cs
Labels: enhancement

#32 Create module for ArmaServerManager commands permissions
  ArmaforcesMissionBot/Handlers/CommandHandler.cs
  ArmaforcesMissionBot/Modules/ArmaServerManager.cs
Labels: bugfix

#33 Modlist link in signups fix
  ArmaforcesMissionBot/Features/Modsets/ModsetProvider.cs
  ArmaforcesMissionBot/Modules/Signups.cs
Labels: bugfix

#34 Fix bot failing to respond on Manager requests
  ArmaforcesMissionBot/ArmaforcesMissionBot.csproj
  ArmaforcesMissionBot/Modules/ArmaServerManager.cs
  ArmaforcesMissionBot/Modules/Mods.cs
  ArmaforcesMissionBot/Modules/Server.cs
  ArmaforcesMissionBot/Modules/ServerConfig.cs
Labels: bugfix

#31 Fix preventing starting multiple signups edit
  ArmaforcesMissionBot/Extensions/SignupsDataExtensions.cs
  ArmaforcesMissionBot/Modules/Signups.cs
Labels: bugfix
